kind: Pod
apiVersion: v1
metadata:
  name: nginx-example-resize
  namespace: zfs-system
spec:
  containers:
  - name: nginx-example-resize
    image: nginx:latest
    volumeMounts:
      - name: zfs-volume
        mountPath: /cache
  volumes:
    - name: zfs-volume
      persistentVolumeClaim:
        claimName: example-pvc-resize
