apiVersion: batch/v1
kind: Job
metadata:
  name: sample-job2
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
      - name: sample-job2
        image: centos:latest
        command: ["echo"]
        args: ["hoge"]
      restartPolicy: Never
