apiVersion: batch/v1
kind: Job
metadata:
  name: sample-job-com-par
spec:
  completions: 5
  parallelism: 2
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: sample-job
        image: centos:latest
        command: ["echo"]
        args: ["hoge"]
      restartPolicy: Never
