apiVersion: batch/v1
kind: Job
metadata:
  name: sample-job-com
spec:
  completions: 5
  parallelism: 1
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: sample-job1
        image: centos:latest
        command: ["echo"]
        args: ["hoge"]
      restartPolicy: Never
