apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-redis1
  namespace: stg
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 200m
        - name: redis
          image: redis:latest
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m
