apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx5
  namespace: prd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          resources:
            requests:
              cpu: 300m
            limits:
              cpu: 500m
