kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: example-pvc
  namespace: stg
  annotations:
    volume.beta.kubernetes.io/storage-class: "zfs-sc"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
