apiVersion: v1
kind: Pod
metadata:
  name: test-projected
spec:
  containers:
  - name: container-test
    image: nginx:latest
    volumeMounts:
    - name: all-in-one
      mountPath: "/projected-volume"
      readOnly: true
  volumes:
  - name: all-in-one
    projected:
      sources:
      - secret:
          name: sample-auth
          items:
            - key: username
              path: secret/data
      - configMap:
          name: sample-configmap2
          items:
            - key: maxmemory
              path: configmap/data
      - downwardAPI:
          items:
            - path: "podname"
              fieldRef:
                fieldPath: metadata.name
