apiVersion: v1
kind: Pod
metadata:
  name: redis2
spec:
  containers:
  - name: redis2
    image: redis:latest
    env:
      - name: MAX_MEMORY
        valueFrom:
          configMapKeyRef:
            name: sample-configmap2
            key: maxmemory
