apiVersion: v1
kind: Pod
metadata:
  name: redis5
spec:
  containers:
    - name: redis5
      image: redis:latest
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: sample-configmap1
        items:
        - key: redis.conf
          path: redis.conf
