apiVersion: v1
kind: Pod
metadata:
  name: redis1
spec:
  containers:
  - name: redis1
    image: redis:latest
    env:
      - name: redis_conf
        valueFrom:
          configMapKeyRef:
            name: sample-configmap1
            key: redis.conf
