apiVersion: v1
kind: Pod
metadata:
  name: redis6
spec:
  containers:
    - name: redis6
      image: redis:latest
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: sample-configmap2
        items:
        - key: maxmemory
          path: redis_maxmemory
