apiVersion: v1
kind: Pod
metadata:
  name: security-context02
spec:
  securityContext:
#    runAsUser: 1000
#    runAsGroup: 3000
#    fsGroup: 2000
    runAsNonRoot: true
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - name: centos7
    image: centos:7
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data/demo
