apiVersion: v1
kind: Pod
metadata:
  name: security-context03
spec:
  containers:
  - name: centos7
    image: centos:7
    command: [ "sh", "-c", "sleep 1h" ]
    securityContext:
      runAsUser: 1000
      runAsGroup: 3000
  - name: centos8
    image: centos:8
    command: [ "sh", "-c", "sleep 1h" ]
