apiVersion: v1
kind: Pod
metadata:
  name: security-context05
spec:
  containers:
  - name: centos7
    image: centos:7
    command: [ "sh", "-c", "sleep 1h" ]
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME"]
  - name: centos8
    image: centos:8
    command: [ "sh", "-c", "sleep 1h" ]
