apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app1
  name: nginx-http
spec:
  containers:
  - name: nginx-http
    image: nginx:latest
    ports:
    - containerPort: 80
    readinessProbe:
      httpGet:
        path: /index.html
        port: 80
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 1
