apiVersion: v1
kind: Service
metadata:
  name: load-balancer
spec:
  ports:
  - name: load-balancer
    port: 8080
    protocol: TCP
    targetPort: 80
    nodePort: 30002
  selector:
    app: nginx-dep
  type: LoadBalancer
  loadBalancerIP: 10.20.30.160
  loadBalancerSourceRanges:
  - 10.20.31.0/28
