apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-dep
spec:
  replicas: 8
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: redis
          image: redis:latest
