apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-http
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    args:
    - /bin/sh
    - -c
    - sleep 30; rm /usr/share/nginx/html/index.html; sleep 600
    livenessProbe:
      httpGet:
        path: /index.html
        port: 80
        scheme: HTTP
      initialDelaySeconds: 3
      periodSeconds: 3
