apiVersion: v1
kind: Pod
metadata:
  name: test-resource-field-ref
spec:
  containers:
    - name: centos
      image: centos:latest
      command:
      - sh
      - -c
      args:
      - tail -f /dev/null
      env:
        - name: REQUESTS_CPU
          valueFrom:
            resourceFieldRef:
              containerName: centos
              resource: requests.cpu
        - name: REQUESTS_MEM
          valueFrom:
            resourceFieldRef:
              containerName: centos
              resource: requests.memory
