apiVersion: v1
kind: Pod
metadata:
  name: sample-secret2
spec:
  containers:
    - name: centos
      image: centos:latest
      command:
      - sh
      - -c
      args:
      - tail -f /dev/null
      envFrom:
      - secretRef:
          name: sample-auth
