apiVersion: v1
kind: Pod
metadata:
  name: sample-secret3
spec:
  containers:
  - name: sample-secret3
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: sample-auth
      items:
      - key: username
        path: my-group/my-username
