apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-stg
  namespace: stg
spec:
  replicas: 4
  selector:
    matchLabels:
      env: prd
  template:
    metadata:
      labels:
        env: prd
    spec:
      containers:
        - name: nginx
          image: nginx:latest
