kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zfs-pvc001
  namespace: dev
  annotations:
    volume.beta.kubernetes.io/storage-class: "zfs-sc"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Mi
