apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-quota
spec:
  replicas: 2
  selector:
    matchLabels:
      env: prd
  template:
    metadata:
      labels:
        env: prd
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          resources:
            requests:
              memory: 100Mi
              cpu: 700m
            limits:
              memory: 200Mi
              cpu: 1200m
        - name: redis
          image: redis:latest
          resources:
            requests:
              memory: 200Mi
              cpu: 800m
            limits:
              memory: 300Mi
              cpu: 1300m
