apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-quota2
spec:
  replicas: 2
  selector:
    matchLabels:
      env: prd
  template:
    metadata:
      labels:
        env: prd
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          resources:
            requests:
              memory: 100Mi
              cpu: 1000m
            limits:
              memory: 200Mi
              cpu: 1500m
