apiVersion: v1
kind: Pod
metadata:
  name: test-downwardapi
spec:
  containers:
    - name: test-downwordapi
      image: nginx:latest
      volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "podname"
            fieldRef:
              fieldPath: metadata.name
          - path: "namespace"
            fieldRef:
              fieldPath: metadata.namespace
          - path: "cpu_request"
            resourceFieldRef:
              containerName: test-downwordapi
              resource: requests.cpu
