apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  selector:
    matchLabels:
      env: prd
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Mi
  storageClassName: slow
