apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim3
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Mi
  storageClassName: slow
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim4
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Mi
  storageClassName: slow
---
