apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim5
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Mi
  storageClassName: slow
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim6
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Mi
  storageClassName: slow
---
