apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-unspecified
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: nginx
          image: nginx:latest

